### ISSUE TITLE
`createFragment` with `<img src="xxx">` will send HTTP request

### ISSUE THREAD

**Issue by JounQin** [kmck/rehype-dom#18]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

https://stackoverflow.com/questions/12747350/using-documentfragment-to-parse-html-without-sending-http-requests

### Solution

Use `DOMParser` and strip outside nodes

### Alternatives

N/A

**Comment by wooorm** [comment]
DOMParser is also used: https://github.com/rehypejs/rehype-dom/blob/74aba95c1ca54084bed019b7c77d1f3de9165eec/packages/rehype-dom-parse/lib/index.js#L54.
I don’t think DOMParser can be used to parse HTML as a fragment though?

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/131995032-3d1ddb96-cbfd-44f7-95e6-438019b85abe.png)

**Comment by wooorm** [comment]
That is a whole document. If you want a whole document, then set `document: true`, and you won’t have this problem.

Note my above comment: “I don’t think DOMParser can be used to parse HTML as a fragment though?”

**Comment by JounQin** [comment]
> Use DOMParser and strip outside nodes

We can do something like `doc.body.children`

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/131995645-405be55d-7ee8-45d0-b0a8-9fcf453e4f90.png)

`<html>/<body>` wrapper seems can just be ignored.

**Comment by wooorm** [comment]
Your suggestion is very close to what is actually happening in the current code?
Can you explain with code how to get a fragment that solves your problems?

**Comment by JounQin** [comment]
I want to get fragment jsx instead of document jsx when integration with `rehype-react`.

I mean `createFragment` should not be used because it will send HTTP request, we should always use `DOMParser`, and for `fragment: true`.

> We can do something like `doc.body.children`

**Comment by JounQin** [comment]
```js
/**
 * @param {string} htmlString
 * @returns {DocumentFragment}
 */
function createFragment(htmlString) {
  const fragment = document.createDocumentFragment()
  const doc = createDocument(htmlString)
  let child
  while (child = doc.body.firstChild) {
    fragment.append(child)
  }

  return fragment
}

/**
 * @param {string} htmlString
 * @returns {Document}
 */
function createDocument(htmlString) {
  return new DOMParser().parseFromString(htmlString, 'text/html')
}
```
