### ISSUE TITLE
rehype-dom: can we unlock dependencies?

### ISSUE THREAD

**Issue by wooorm** [kmck/rehype-dom#2]
https://github.com/rehypejs/rehype-dom/blob/5f9d5e04ae5b2819f28b7a21db322daada44974f/packages/rehype-dom/package.json#L34-L35

@kmck What’s the reason for having them locked? My thinking is that if we use semver, we can unlock them. And for anyone who doesn’t trust semver, there’s lockfiles?
Can we unlock them?

**Comment by kmck** [comment]
should be fine to change to a `^` version. i think it might have just been an oversight on my part when setting up the monorepo, but i'd wanna double-check to make sure the workflow is still straightforward

**Comment by wooorm** [comment]
I think it’ll be fine, I’ve been using it for remark/rehype/retext and haven’t run into problems!

**Comment by wooorm** [comment]
(I don’t use yarn enough, but I feel like yarn workspaces wouldn‘t be a problem either?)

**Comment by kmck** [comment]
yup, seems safe to change! just tested the loosened restrictions locally with the current version and bumped versions everything still resolved as expected.

**Comment by wooorm** [comment]
Alright, I’ll loosen them and cut the releases!

**Comment by wooorm** [comment]
Done! ✨
