### ISSUE TITLE
Don't escape the text content in style

### ISSUE THREAD

**Issue by wqcstrong** [kmck/rehype-dom#21]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

```js
import rehypeDomParse from 'rehype-dom-parse';
import rehypeDomStrigify from 'rehype-dom-stringify';

const htmlString = `
<style>
  body > div {
    width: 100px;
  }
</style>
`;

console.log(
  unified()
    .use(rehypeDomParse)
    .use(rehypeDomStrigify)
    .processSync(htmlString)
    .toString(),
);

```

Actually output: 
```html
<style>
  body &gt; div {
    width: 100px;
  }
</style>
```

### Solution

Expected output:
```html
<style>
  body > div {
    width: 100px;
  }
</style>
```

### Alternatives

/

**Comment by wooorm** [comment]
Hmm, yeah, bug.
You can try this in a browser. It a) should show the style in red text, b) shows that it’s the `XMLSerializer` that does this:

```js
document.body.innerHTML = `<style>
  body > style {
    display: block; color: red;
  }
</style>`;
console.log(document.body.innerHTML)
new XMLSerializer().serializeToString(document.body)
````

**Comment by wooorm** [comment]
I have a PR, could you check it?

**Comment by wqcstrong** [comment]
😁 I have just reviewd the core implement

Thanks for your job, bro!
